// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.practice.pb;

public interface AddressBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.practice.AddressBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.practice.Person person = 1;</code>
   */
  boolean hasPerson();
  /**
   * <code>optional .com.practice.Person person = 1;</code>
   */
  com.practice.pb.Person getPerson();
  /**
   * <code>optional .com.practice.Person person = 1;</code>
   */
  com.practice.pb.PersonOrBuilder getPersonOrBuilder();
}
