// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.practice.pb;

public interface AddressBookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.practice.AddressBookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
