// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.practice.pb;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.practice.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.practice.Person person = 1;</code>
   */
  java.util.List<com.practice.pb.Person> 
      getPersonList();
  /**
   * <code>repeated .com.practice.Person person = 1;</code>
   */
  com.practice.pb.Person getPerson(int index);
  /**
   * <code>repeated .com.practice.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .com.practice.Person person = 1;</code>
   */
  java.util.List<? extends com.practice.pb.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .com.practice.Person person = 1;</code>
   */
  com.practice.pb.PersonOrBuilder getPersonOrBuilder(
      int index);
}
