// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.practice.pb;

public final class AddressBookProto {
  private AddressBookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_practice_AddressBookRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_practice_AddressBookRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_practice_AddressBookResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_practice_AddressBookResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_practice_Person_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_practice_Person_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_practice_Person_PhoneNumber_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_practice_Person_PhoneNumber_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_practice_AddressBook_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_practice_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\014com.practice\" \n\022Add" +
      "ressBookRequest\022\n\n\002id\030\001 \001(\005\";\n\023AddressBo" +
      "okResponse\022$\n\006person\030\001 \001(\0132\024.com.practic" +
      "e.Person\"\334\001\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030" +
      "\002 \001(\005\022\r\n\005email\030\003 \001(\t\022/\n\005phone\030\004 \003(\0132 .co" +
      "m.practice.Person.PhoneNumber\032K\n\013PhoneNu" +
      "mber\022\016\n\006number\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.com" +
      ".practice.Person.PhoneType\"+\n\tPhoneType\022" +
      "\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"3\n\013Addre" +
      "ssBook\022$\n\006person\030\001 \003(\0132\024.com.practice.Pe",
      "rson2d\n\022AddressBookService\022N\n\005query\022 .co" +
      "m.practice.AddressBookRequest\032!.com.prac" +
      "tice.AddressBookResponse\"\000B\'\n\017com.practi" +
      "ce.pbB\020AddressBookProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_practice_AddressBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_practice_AddressBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_practice_AddressBookRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_practice_AddressBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_practice_AddressBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_practice_AddressBookResponse_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_com_practice_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_practice_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_practice_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phone", });
    internal_static_com_practice_Person_PhoneNumber_descriptor =
      internal_static_com_practice_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_practice_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_practice_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_practice_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_practice_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_practice_AddressBook_descriptor,
        new java.lang.String[] { "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
