// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.practice.pb;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.practice.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .com.practice.Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<com.practice.pb.Person.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .com.practice.Person.PhoneNumber phone = 4;</code>
   */
  com.practice.pb.Person.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .com.practice.Person.PhoneNumber phone = 4;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .com.practice.Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<? extends com.practice.pb.Person.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .com.practice.Person.PhoneNumber phone = 4;</code>
   */
  com.practice.pb.Person.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
