:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 6-3 コーディングのヒント

=== Spring Bean

Spring Framework によって管理されるクラスのことを Bean と呼びます。
Path という String 型のメンバ変数（プロパティ）を持つクラスを宣言します。

[source,java]
----
include::../projects/chapter6/src/main/java/com/example/vocabularybook/chapter6/hints/Hint1.java[]
----

=== applicationContext.xml（設定ファイル）

クラスを Bean として宣言し、設定ファイル中で自由に利用することができます。

[source,xml]
.applicationContext.xml
----
include::../projects/chapter6/src/main/java/com/example/vocabularybook/chapter6/hints/applicationContext.xml[]
----

(1) 前述の Hint1 クラスを hintBean1 として Spring Framework に登録・宣言します。
プロパティにも代入しておきます。

(2) Hint1 クラスを Hint2 クラスのプロパティに代入します。

=== Spring Bean を利用する

設定ファイルで宣言したファイルを利用してみましょう。

[source,java]
----
include::../projects/chapter6/src/main/java/com/example/vocabularybook/chapter6/hints/Hint2.java[]
----
<1> 設定ファイルを読み込みます。
<2> 設定ファイル内で宣言されている Bean のインスタンスを取得します。
<3> 上記で取得したインスタンスの関数（メソッド）を実行します

=== ライブラリの追加
Spring Framework を利用するためには、ライブラリの追加が必要です。教材格納場所から jar ファイルをダウンロードし、Eclipse に追加してください。

====
* spring-tx-3.0.0.RELEASE.jar
* spring-jdbc-3.0.0.RELEASE.jar
* spring-expression-3.0.0.RELEASE.jar
* spring-core-3.0.0.RELEASE.jar
* spring-context-3.0.0.RELEASE.jar
* spring-beans-3.0.0.RELEASE.jar
* spring-asm-3.0.0.RELEASE.jar
* spring-aop-3.0.0.RELEASE.jar
* hamcrest-core-1.3.jar
* junit-4.12.jar
* commons-logging-1.1.1.jar
* h2-1.4.199.jar
* aopalliance-1.0.jar
====

=== 次のセクションでは…

次のセクションでは、コーディング例を示します。
自分がコーディングした内容と比較してみましょう。

* link:chapter6-4.html[Chapter 6-4 コーディング例]

== リンク

* link:chapter6-1.html[Chapter 6-1 Spring Framework 適用（DI）]
* link:chapter6-2.html[Chapter 6-2 Spring Framework とは]
* link:chapter6-3.html[Chapter 6-3 コーディングのヒント]
* link:chapter6-4.html[Chapter 6-4 コーディング例]
* link:chapter6-5.html[Chapter 6-5 テストの修正]
* link:chapter6-6.html[Chapter 6-6 テストのコーディング例]
