:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 8-2 Web の基礎知識

=== WWW(World Wide Web)について

``WWW`` はインターネット上でドキュメントを相互に結びつけるための仕組みです。
ドキュメントそのものは``インターネット``に接続されているコンピュータに格納され、一定の作法によってドキュメントを取り出すことができます。

=== プロトコルについて

「一定の作法」のことを``プロトコル``と呼びます。
プロトコルにはいろいろな種類がありますが、ドキュメントをやり取りするものは、``http(Hyper Text Transfer Protocol)``と呼びます。

==== その他のプロトコル

.プロトコルまとめ
|===
|プロトコル名|機能

|HTTP(Hyper Text Transfer Protocol)
|ドキュメントをやり取りする

|HTTPS(Hyper Text Transfer Protocol Secure)
(SSL/TLS)
|やり取りの内容を暗号化する（正確にはプロトコルではないが、ここで一緒に紹介する）

|FTP(File Transfer Protocol)
|ファイルをやり取りする

|SMTP(Simple Mail Transfer Protocol)
|メールを送信する

|===

=== HTTPメッセージ

HTTPは一定の作法によってコンピュータ間の通信を行うと説明しましたが、
行きと帰りの情報のことを``リクエストメッセージ``と``レスポンスメッセージ``と呼びます。

==== リクエストメッセージ

リクエスト行、ヘッダーフィールド、ボディで構成されます。

==== レスポンスメッセージ

ステータス行、ヘッダーフィールド、ボディで構成されます。

=== URLとIPアドレス

``インターネット``に接続されている全てのコンピュータには場所を示す``IPアドレス``が付与されています。
この``IPアドレス``をたどって目的のコンピュータにたどり着くことができます。
アドレスは無味乾燥な数字や英字で構成されているため、覚えるには不向きです。
それを解決するために、``IPアドレス``には任意の名前（``FQDN``）をつける事ができます。

このコンピュータの名前と前述のプロトコル、コンピュータ内のドキュメントの位置をつなげて、一連の文字列にしたものをURLと呼びます。

=== Webサーバーについて

ドキュメントを格納するコンピュータのことをWebサーバーと呼びます。
常時通電され、ドキュメントの取り出し要求に備えています。

=== Webクライアントについて

一方、ドキュメントを取り出すコンピュータをWebクライアントと呼びます。

=== Webブラウザについて

ドキュメントをやり取りするためのソフトウェアはいろいろな種類がありますが、
最も一般的なものはWebブラウザでしょう。
WebブラウザはWebサーバーとのやりとりや、HTMLを解釈して画面に表示するなど、様々なドキュメントに関する仕事を引き受けてくれます。

=== HTML について

ドキュメントは ``HTML(Hypertext Markup Language)`` と呼ばれる専用の記法で記述されます。
ドキュメントの内容は人が解釈することができるテキスト形式で記述します。

``HTML``の一番の特徴は、ドキュメント間を結びつけることができる``リンク``という機能です。
このようなドキュメントのことを``ハイパーテキスト``と呼びます。
``http``は``Hypertext Transfer Protocol``と説明しましたが、``ハイパーテキスト``というのは``HTML``で記述されたドキュメントを示しているのです。
（HTTPはHypertextだけではなく、画像ファイルなどのバイナリ転送もサポートしています）

=== HTML の基本構造

HTMLは、ドキュメントの本文だけではなく、目に見えない数々の情報も記述することができます。
基本的には以下のように情報は配置されます。

.HTMLの領域まとめ
[cols="1,3a"]
|===
|領域の名称|記述される情報

|head
|
* どんな言語で記述されているのか
* タイトル
* 作者・著者
* 他

|body
|ドキュメントの本文を記述する領域です。

|===

=== タグと要素（エレメント）と属性（アトリビュート）

HTMLのもう一つの特徴としては、タグの利用があります。
タグとは、以下のサンプルのように、文章を``<a>``と``</a>``で囲むことで、ドキュメントに意味づけをしていきます。
``Markup Language``と名付けられているのにはこういった意味があります（マークアップとはマークを付けること）

[source,html]
----
これは別のページへの<a href="other-page.html">リンク</a>です。
----

タグで囲まれた文章を要素（エレメント）と呼びます。
また、要素（エレメント）にはさらなる情報として、属性（アトリビュート）を設定することができます。
上の例では``href``という属性（アトリビュート）を要素（エレメント）に付与しています。

用途によって使い分けができるように複数のタグが用意されています。
タグによって、利用できる属性（アトリビュート）が決まっています。

.HTMLのタグ
[cols="1,3a"]
|===
|タグ名称|どのような場所で利用されるか

|H1, H2, H3, ...
|文章のまとまりの初めに置かれる、見出し（Header）を示します。
数字がついていることからもわかるように、階層構造を構成することができます。

|p
|文章を示します。

|ol, ul, dl
|リストを示します。

* ol … 順番付きリスト
* ul … 順番なしリスト
* ol … 見出し付きリスト

|a
|他のドキュメントへのリンクを設置できます。

|hr
|罫線を引くことができます。

|table, th, td
|表を設置できます。

|form
|データをサーバーに送信するためのまとめ役をこなします。

|input, select と option
|ユーザーからの入力を受け取り、サーバーへ送信するための値を保持します。

|===

タグで囲むことによって、Webブラウザにはそのタグに即した形式で表示されます。
この表示方法はWebブラウザの初期設定で決まっていますが、表示方法はドキュメントの製作者が自由に設定することができます。
これをスタイルと呼びますが、このドキュメントでは詳しく解説しません。

=== フォーム

タグの中でも、他のタグとは異なる特別な意味を持ちます。
``formタグ``は通常は内部にいくつかの``inputタグ``を持ち、それらの情報をサーバーへ送ることができます。

=== POSTメソッドとGETメソッド

form でサーバーへ情報を送ることができると記述しましたが、その方法は８つあります。
送信の方法はメソッドと呼ばれ、ここでは、そのうち代表的なGETメソッドとPOSTメソッドの２つを紹介します。

ちなみに、``https``を利用して情報のやり取りを行った場合、``GET``と``POST``どちらの方法でも情報が暗号化されて送られます。

==== GETメソッド

サーバー上のリソースを取得するときに利用します。
GETメソッドでサーバーへ情報を送る場合、URLの末尾に情報が付加されて送られます。
ブラウザのアドレスバーに表示されるため、付加された情報がわかります。

[source]
----
http://example.com/index.html?name=john&age=18
----

末尾に``?``がついていることがわかりますか？
その後、``名前=値``の組が``&``で接続されていることもわかると思います。

==== POSTメソッド

クライアントがサーバー上にデータを送信する場合に利用します。
POSTメソッドでサーバーへ情報を送る場合、リクエストのボディ部分に情報が設定されて送られます。

=== Webサーバーとアプリケーションサーバー

ここまではWebサーバーやHTMLばかりが登場してきましたが、Javaはどうなってしまったのでしょう。
大規模な開発では、役割によってサーバーを分けることがよくあります。

Webサーバーは基本的に静的なリソースを返却することに利用します。
データを登録したり、パラメータによって動機なリソースを返却することはできません。

これを担当するのがアプリケーションサーバーというわけです。
アプリケーションサーバーはWebサーバーと同じく、Javaなどを実行できるソフトウエアがクライアントからの要求に対して待機します。
Webサーバーは自分のところで実行できない部分をアプリケーションサーバーに受け渡すというわけです。

=== HTML以外のドキュメントについて

ここまで、Webでやり取りされるのはHTMLであると記述してきましたが、
この他にも用途によって多種多様なドキュメントが使い分けられます。
その種類は今後も増えていくことでしょう。

=== 次のセクションでは…

Servlet, JSP を利用した Web コーディングの方法を学びます。

* link:chapter8-3.html[Chapter 8-3 コーディングのヒント]

=== リンク

* link:chapter8-1.html[Chapter 8-1 （機能追加）サービスを Web に公開する]
* link:chapter8-2.html[Chapter 8-2 Web の基礎知識]
* link:chapter8-3.html[Chapter 8-3 コーディングのヒント]
* link:chapter8-4.html[Chapter 8-4 コーディング例]
* link:chapter8-5.html[Chapter 8-5 テストの修正]
* link:chapter8-6.html[Chapter 8-6 テストのコーディング例]
