:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 8-4 コーディング例

[source,java]
.MainServer.java
----
include::../projects/chapter8/src/main/java/com/example/vocabularybook/chapter8/MainServer.java[]
----

=== web.xml

[source,xml]
.webapp/WEB-INF/web.xml
----
include::../projects/chapter8/src/main/java/webapp/WEB-INF/web.xml[]
----

=== Servlet（サーブレット）

[source,java]
.BookTranslateServlet.java
----
include::../projects/chapter8/src/main/java/com/example/vocabularybook/chapter8/handler/BookTranslateServlet.java[]
----
<1> form で送出したパラメータを読み込みます。
<2> Spring Bean の読み込みをアプリケーション・サーバーに任せたので、利用するときもアプリケーション・サーバーから取得します。
<3> Spring Bean を取得することができたので、ビジネスロジックを実行できます。
<4> 処理結果を属性値として設定します。
<5> 上記処理が終わったあとの画面遷移先を設定します。

[source,java]
.BookAddServlet.java
----
include::../projects/chapter8/src/main/java/com/example/vocabularybook/chapter8/handler/BookAddServlet.java[]
----

[source,java]
.BookDeleteServlet.java
----
include::../projects/chapter8/src/main/java/com/example/vocabularybook/chapter8/handler/BookDeleteServlet.java[]
----

=== JSP(Java Server Pages)

[source,html]
.webapp/index.jsp
----
include::../projects/chapter8/src/main/java/webapp/index.jsp[]
----
リソースを取得（翻訳結果を取得）するときなど、更新を伴わないアクセスのときは Get メソッドを利用してください。

[source,html]
.webapp/management.jsp
----
include::../projects/chapter8/src/main/java/webapp/management.jsp[]
----
単語の追加や削除は、リソースに変化を与えるため、Post メソッドを利用します。

=== 次のセクションでは…

では、次はテストの修正です。Web へのアクセスを伴うテストは、今までのテストとは若干異なります。

* link:chapter8-5.html[Chapter 8-5 テストの修正]

=== リンク

* link:chapter8-1.html[Chapter 8-1 （機能追加）サービスを Web に公開する]
* link:chapter8-2.html[Chapter 8-2 Web の基礎知識]
* link:chapter8-3.html[Chapter 8-3 コーディングのヒント]
* link:chapter8-4.html[Chapter 8-4 コーディング例]
* link:chapter8-5.html[Chapter 8-5 テストの修正]
* link:chapter8-6.html[Chapter 8-6 テストのコーディング例]
