:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 3-3 インターフェイスの設計

=== インターフェイスとは

インターフェイスの説明でよく出てくるのが、電源のコンセント・差込プラグです。
（日本では）細長い差込口が２つあるあれです。
コンセント側は何が差し込まれるか全く知りませんが、差し込まれることで電源を供給する役目を果たします。

インターフェイスを一言でいうと「やり取りするための決まりごと」です。
コンセントの例では、差込口の２つの穴の大きさや幅が決まっているので、
形状があっていれば差し込んで使うことができます。

前のセクションで、上位のレイヤーが下位のレイヤーを利用していましたが、
下位のレイヤーがコンセント、上位のレイヤーが差込プラグと置き換えて考えてみてください。
レイヤー分割をすることで、各々のレイヤーの役割を分ける事ができたので、
今度はレイヤーの間のやり取りを設計しようというわけです。

レイヤーは３層作成しましたが、
インターフェイスは使われる側のみ考えればいいので、
今回設計するインターフェイスは２つです。

=== ビジネスロジックインターフェイスを考える

まずはインターフェイスの名前を決めます。
翻訳アプリなので、「TranslateLogic」としましょう。

ビジネスロジックインターフェイスは、プレゼンテーション層からコマンドを受け取って、 実行結果を返します。
コマンドを実行するメソッドを宣言します。メソッド名は「execute」としましょう。

==== DTO について
インターフェイスのメソッドを設計していますが、 問題は引数と戻り値です。
単純に文字列型を引数に…と考えがちですが、将来引数や戻り値を増やしたり、型を変更したくなった場合、
インターフェイスそのものを変える必要が出てきます。

これは、コンセントの穴が足りなくなったから、もう一つ増やそうと言っているのと同じことで、
インターフェイスはできるだけ変更しないように設計するのが上策です。

ここでは、引数と戻り値それぞれに専用のクラスを用意して、やり取りすることにします。
やり取り専用のクラスは構造体のように、メンバー変数が宣言されている単純なクラスです。
このようなクラスのことをDTO（Data Transfer Object）と呼びます。
引数や戻り値を変更したくなった場合は、このクラスのメンバー変数を変更するというわけです。

===== input
引数のためのDTOです。
「TranslateLoginInDTO」と名付け、
メンバー変数にはプレゼンテーションからの入力をそのまま入れる、
文字列型の「command」を宣言しましょう。

===== output
戻り地のためのDTOです。
「TranslateLoginOutDTO」と名付けます。

まずはLogicからのメッセージを格納する文字列型「message」を宣言します。
問題は終了判定ですが、こちらは論理型（boolean）「terminate」を宣言して、
アプリを終了するかどうかの判断をしてもらうことにします。


=== データアクセスインターフェイスを考える

こちらもまずインターフェイスの名前を決めます。
単語帳にアクセスするので、「BookAccessor」としましょう。

単語帳には次の３つの機能が必要です。

* 単語の追加
* 単語の削除
* 単語を探す

これら３つをメソッドとして宣言してください。
データアクセスインターフェイスもDTOを利用してもいいのですが、
データの構造も単純なので、文字列型などを利用するやり方にとどめます。

=== 次のセクションでは…

次のセクションでは、インターフェイスのコーディング例を示します。

* link:chapter3-4.html[Chapter 3-4 インターフェイスのコーディング例]

=== リンク

* link:chapter3-1.html[Chapter 3-1 コードを整理する]
* link:chapter3-2.html[Chapter 3-2 整理の方針]
* link:chapter3-3.html[Chapter 3-3 インターフェイスの設計]
* link:chapter3-4.html[Chapter 3-4 インターフェイスコーディング例]
* link:chapter3-5.html[Chapter 3-5 インターフェイスを実装する]
* link:chapter3-6.html[Chapter 3-6 コーディング例]
* link:chapter3-7.html[Chapter 3-7 テストの作成]
* link:chapter3-8.html[Chapter 3-8 テストコーディング例]
