:toc: left
:source-highlighter: coderay
:experimental:

== Chapter Extended 1-2 概要

=== アプリ間通信について

古くから、アプリ間で情報をやり取りしたいというニーズはあったようです。
やり取りされるのは、なにもデータだけではありません。
アプリの機能そのものも共有したいという要求があるのです。

他のアプリに実装されている機能を使いたいと思ったことはありませんか？
それが実現できれば、コードの重複を防げますし、データの秘匿性を保つこともできます。

=== RPCについて

別のメモリ空間やネットワーク越しのアプリの機能を、あたかも関数を利用するかのごとく呼び出すことができる仕組みを
RPC（リモート・プロシージャ・コール）と呼びます。

これを実現するライブラリはいくつかあります。
以下に少しだけ紹介します。

.RPCライブラリ

|===
|ライブラリ名|開発・メンテナ

|gRPC
|Google

|Thrift
|Apache

|Apache Avro
|Apache

|===

=== Thrift（スリフト）について

ThriftはFacebookが開発し、Apacheに寄贈した、オープンソースのRPCライブラリです。

==== IDL

Thriftが特徴的なのは、IDL（インターフェイス定義言語）を使ってインターフェイス定義を記述し、
Thriftのコンパイラにかけると、サーバー側、クライアント側の通信に関わるコードを自動生成してくれるところです。

インターフェイスの定義は仕様書などで交わされますが、仕様書と実際のコードが乖離してしまうことは珍しくありません。
ThriftのIDLはとても簡易な記法のため、直感的にどのような定義がされているかをつかむことができます。
また、CSVのようなフラットなデータ構造だけではなく、階層構造を持つデータを扱うこともできます。

==== 多言語への対応

Thriftは多種多様な言語に対してコード生成を行うことができるため、
例えば、サーバー側をJavaで記述し、クライアント側を``Swift``や``C#``などで記述することもできます。
異なる言語間でも型情報は失われず、各言語の適切な型に変換されます。

今チャプターでは、サーバー側をこれまで作成してきたJava、クライアント側をC#（Windows Forms）で作成します。

==== 通信経路について

http/https上でデータをやり取りするため、
既存のネットワークをそのまま利用することができます。

==== やり取りされるデータについて

XMLやJSONなどのテキストベースのデータとは異なり、バイナリベースでデータをやり取りするため、
データサイズが小さくすみ、パフォーマンスを犠牲にしません。

==== アプリへの組み込み

サーブレットとしてアプリに組み込むこともできるため、
すでに運用されているアプリにも比較的簡単に組み込むことができます。

=== 次のセクションでは…

ThriftのIDLでインターフェイスを定義し、コード生成を行います。

* link:chapterExtended1-3.html[Chapter Extended 1-3 IDLの定義とコード生成]

=== リンク

* link:chapterExtended1-1.html[Chapter Extended 1-1 C#(Windows Forms)からサービスを利用する]
* link:chapterExtended1-2.html[Chapter Extended 1-2 概要]
* link:chapterExtended1-3.html[Chapter Extended 1-3 IDLの定義とコード生成]
* link:chapterExtended1-4.html[Chapter Extended 1-4 サーバー側コーディング例]
* link:chapterExtended1-5.html[Chapter Extended 1-5 クライアント側コーディング例]
