:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 3-6 コーディング例

=== データアクセス

.BookOnMemoryImpl.java
[source,java,indent=0]
----
include::../projects/chapter3/src/main/java/com/example/vocabularybook/chapter3/dataaccess/BookOnMemoryImpl.java[]
----

メソッドのやり取りはインターフェイスに対して行っていることに注目。
実装クラスはインスタンス生成のときのみ出現している。

=== ビジネスロジック

.TranslateLogicImpl.java
[source,java,indent=0]
----
include::../projects/chapter3/src/main/java/com/example/vocabularybook/chapter3/logic/TranslateLogicImpl.java[]
----

下位のレイヤーのデータアクセスのみimportしている。上位のMainクラスは参照していない。

=== プレゼンテーション
今回はコンソールを利用して入出力を行うため、プレゼンテーションのクラスはわざわざ作成しませんでした。

.Main.java
[source,java,indent=0]
----
include::../projects/chapter3/src/main/java/com/example/vocabularybook/chapter3/Main.java[]
----

データアクセス層のクラスが出現しないことに注目。



=== 次のセクションでは…

ユニットテストを行います。
ユニットテストをコーディングしておくことで、 コードを安心して触ることができます。
コードになにか手を加えて、ユニットテストが不合格だった場合、そこに影響があることがわかるからです。

ユニットテストは未来の自分への投資です。

* link:chapter3-7.html[Chapter 3-7 テストの作成]

=== リンク

* link:chapter3-1.html[Chapter 3-1 コードを整理する]
* link:chapter3-2.html[Chapter 3-2 整理の方針]
* link:chapter3-3.html[Chapter 3-3 インターフェイスの設計]
* link:chapter3-4.html[Chapter 3-4 インターフェイスコーディング例]
* link:chapter3-5.html[Chapter 3-5 インターフェイスを実装する]
* link:chapter3-6.html[Chapter 3-6 コーディング例]
* link:chapter3-7.html[Chapter 3-7 テストの作成]
* link:chapter3-8.html[Chapter 3-8 テストコーディング例]
