:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 2-3 コーディングのヒント

=== 単語の保持にはMapを使う
前回と異なり、単語の格納にはMapを利用します。
Mapは今作っている単語帳を実現するためにはうってつけの道具です。

インスタンスを生成したときには中身には何も入っていませんが、実行中にアイテムを任意のタイミングで追加・削除することができます。
MapはKeyとValueという２つの要素をペアで保持することができます。今回の単語帳アプリでは、Keyに単語、Valueに翻訳単語を保持することにしましょう。

さて、Mapにアイテムを追加したとして、それを探すのはどのように行うのでしょうか？
配列では中身から何かを探すときにループなどを使って、頭から順番に走査しましたが、それと同じ方法を使うのでしょうか？
いえいえ、Mapには保持したアイテムを一意に特定する方法を持っています。
Mapはこのような特性を持っているため、（Key部分の）重複を許可していません。
すでに登録済みのキーを追加しようとすると、新しい値で上書きされてしまうのです。

.Mapインターフェイスの代表的なメソッド
|===
|メソッド|処理内容

|put
|アイテムを追加する

|remove
|アイテムを削除する

|containsKey
|アイテムがあるかどうか確認する
|===

[source,java,indent=0]
.コード例
----
include::../projects/chapter2/src/main/java/com/example/vocabularybook/chapter2/hints/Hint1.java[lines=8..14]
----
Mapを宣言するときに、気になることが２つあります。

. 変数の型はMapなのに、その変数にはHashMapのインスタンスを代入している
+
Mapはインターフェイス、HashMapはクラスなのですが、この違いは次のチャプターで詳しく説明します。

. Mapのすぐ後ろに<String, String>が記述されているが、これは何？
+
MapにはKey、Valueの２つの要素を保持できることは先程も書きましたが、この２つの要素のそれぞれの型を指定することができます。
型を指定することでMapに入れることができるアイテムがより厳密になります。
言語機能的には「ジェネリクス」や「総称型」と呼ばれるものです。
+
[source,java,indent=0]
----
include::../projects/chapter2/src/main/java/com/example/vocabularybook/chapter2/hints/Hint2.java[lines=8..13]
----
+
型指定はオプションで指定しないこともできますが、指定しない場合はコンパイラから警告を受けるでしょう。

=== 変数のスコープとライフサイクル
newキーワードを用いてインスタンスを生成し、それを変数に代入して利用するわけですが、 インスタンスには寿命があります。
基本的にそれが宣言されたブロックから抜けるとインスタンスは寿命を迎えます。

[source,java,indent=0]
----
include::../projects/chapter2/src/main/java/com/example/vocabularybook/chapter2/hints/Hint4.java[lines=6..23]
----
上記の例では次のようになります

<1> mainメソッドが終了するまで
<2> ifブロックを抜けるまで
<3> doSomethingメソッドが終了するまで

=== コマンドをパース（分解・解析）する
今回、コマンドはスペースで要素に分解することができます。
StringクラスのSplitメソッドを利用してそれぞれの要素に分解しましょう。
コマンドによって、要素の数が違うことが心配ですか？
安心してください。要素の数だけ自動的に配列が作られるので、どのコマンドにも対応できます。

[source,java,indent=0]
----
include::../projects/chapter2/src/main/java/com/example/vocabularybook/chapter2/hints/Hint3.java[lines=5..9]
----

ただし、配列外のところにアクセスしようとするとエラーが発生してしてしまいます。
読み取るときは注意して読み取ってください。

=== コマンドの失敗
今回の仕様の中でコマンドの失敗は以下の２つと考えていいでしょう。

* （入力なし）「T」「A」「D」以外のコマンドを指定した場合
* 配列で範囲外にアクセスしてしまった場合


=== 今日のショートカット（Eclipse）

.今日のショートカット
|===
|ショートカット|目的

|kbd:[Alt + 上下カーソルキー]
|選択行を移動する

|kbd:[Alt + Shift + 上下カーソルキー]
|選択行を複製する

|kbd:[Ctrl + D]
|選択行を削除する

|kbd:[Ctrl + /]
|選択行をコメント化する

|行を選択して、kbd:[Alt + Shift + Z]
|選択行を囲んで文を追加
|===

=== 次のセクションでは…

次のセクションでは、コーディング例を示します。
自分がコーディングした内容と比較してみましょう。

* link:chapter2-4.html[Chapter 2-4 コーディング例]

== リンク

* link:chapter2-1.html[Chapter 2-1 (機能追加)単語を登録・削除する機能を追加]
* link:chapter2-2.html[Chapter 2-2 設計のヒント]
* link:chapter2-3.html[Chapter 2-3 コーディングのヒント]
* link:chapter2-4.html[Chapter 2-4 コーディング例]
