:toc: left
:source-highlighter: coderay
:experimental:

== Chapter 4-6 テストコーディング例

=== ロジック層のテスト

.TranslateLogicTest.java
[source,java,indent=0]
----
include::../projects/chapter4/src/test/java/com/example/vocabularybook/chapter4/logic/TranslateLogicTest.java[]
----
<1> メモリに格納した場合、インスタンスが破棄されてしまえば、メモリの内容は破棄されてしまいます。
しかし、ファイルに格納した場合は単語はファイルに保存されるため、単語は登録されたまま！

コードの実装を変更した後に前回のテストを実施すると、エラーが発生することに注目してください。
エラーが発生することで、変化点をあぶり出すことができます。このことからも、テストの重要性がわかってもらえるでしょうか？

=== データアクセス層のテスト

.BookOnFileImplTest.java
[source,java,indent=0]
----
include::../projects/chapter4/src/test/java/com/example/vocabularybook/chapter4/dataaccess/BookOnFileImplTest.java[]
----


=== 次のチャプターでは…
いよいよ、業務アプリケーションにつきもののデータベースが登場です。
今回はファイルに保存しましたが、次回ではデータベースに単語を登録していきます。
驚くほど少ない変更でデータベース対応できることに注目してください。

* link:chapter5-1.html[Chapter 5 (機能追加)データベースに保存する機能を追加]

=== リンク

* link:chapter4-1.html[Chapter 4-1 (機能追加)ファイルに保存する機能を追加]
* link:chapter4-2.html[Chapter 4-2 設計のヒント]
* link:chapter4-3.html[Chapter 4-3 コーディングのヒント]
* link:chapter4-4.html[Chapter 4-4 コーディング例]
* link:chapter4-5.html[Chapter 4-5 テストの修正]
* link:chapter4-6.html[Chapter 4-6 テストのコーディング例]
