:toc:
:source-highlighter: coderay
:experimental:

= コーディングスキル勉強会

== Chapter 0 はじめに

``コーディングスキル``という言葉を考えたときに、それが指し示すものは何なのでしょう？
プログラミング言語の文法を知っていることでしょうか？それとも仕様をコード化することでしょうか？

=== どんな読者向けに書かれているか

思い当たることが一つでもあれば、あなたのコーディングスキル向上のお役に立ちます。

* プログラミングの基本は覚えたけれど、次に何をするのかがわからない。
* 簡単なプログラムを組むことはできるけど、規模が大きくなると収拾がつかない。
* フレームワークに沿った書き方はできるけれど、自分ではじめからと言われると困ってしまう。

=== 身につくスキル

このテキストでは``Java``を利用しますが、考え方は他の言語でも利用することができます。
まずはじめに簡単なアプリを作り、そこに機能をどんどん追加していきます。
そのため、機能追加。変更に強いコーディングスキルを身につけることができます。

テキストの中盤をすぎる頃には、大規模なアプリケーションを構築することができるスキルを身につけることができるでしょう。

テキストの後半では、``Spring Framework``をアプリに適用します。
``Spring Framework``がどのような機能を持っていて、どのような目的をもって作られているのかを知ることができます。
もし、あなたがこの先、アプリを一から作ることになった場合でも``Spring Framework``を有効に使うことができます。

また、おまけ要素として、``Eclipse``のショートカットも載せていますから、
コーディングスピードの向上も期待できます。

=== このテキストの使い方
このテキストではいくつかの章で構成されていますが、
一つの章を終えると一通りの機能を持つアプリを手に入れることができます。

一つの賞は4つのセクションに分かれていて、それぞれセクションでは以下の内容が書かれています。
次のセクションに行く前に自分の頭で考えて見ることをおすすめします。

. お客様からどんなアプリを作って欲しいかの要望
. 要望を分解してどんなアプリを作るのかを設計する
. コーディングを行う上でのヒント
. コーディング例

==== リンク

link:chapter1-1.html[Chapter 1]