:toc: left
:source-highlighter: coderay
:experimental:

= コーディングスキル勉強会

== Chapter 0 はじめに

コーディング好きですか？

序文として何を書くのか悩みましたが、コーディングのどんなところが好きなのかを書くことにしました。

コーディングは何かと言われたら、多少の繰り返しや分岐はあるものの「処理を文字で記述すること」ですよね。
言葉にしてしまうと平坦で深みなどはあまり感じません。こんなものに面白みがあるのかと言われると、
この言葉の内側にいるうちは深みも面白さも感じることはできないでしょう。

さて、最近のプログラミング言語には、関数やクラスといった機能が備わっています。
関数もクラスも、コードを一定のルールで整理するための仕組みなのですが、
これらを上手に使ってやることで、コーディングはたちまち平坦なものから立体的な構造物をつくる行動に成り代わります。
さらに工夫をこらすことで、構造物は堅牢さを増し、ちょっとのことでは壊れないものになります。

立体的な構造物…現実世界では家などの建物や橋など色々とありますが、
物として目の前に出現したとき、私達は建築した人たちに思いを馳せることができます。
「これはなんのために建てられたのか」「どのように建てたのか」「こんな工夫がされている！」
つまり、構造物を介して意思疎通を行っているのです。

絵を見たり、音楽を聞いたりするとき、絵画や音楽の技法を知っているだけで、
見かた、聞きかたが変わってきませんか？

コーディングも意思を持って行えば、 他の人やチームメンバー（そして未来の自分にも）に意思を伝えられます。
あなたも、コーディングを通して意思を伝えられるようになってみませんか？

=== どんな読者向けに書かれているか

次の項目に思い当たることが一つでもあれば、あなたのコーディングスキル向上の足しになるでしょう。

* プログラミング言語の基本は覚えたけれど、次に何をするのかがわからない。
* 簡単なプログラムを組むことはできるけど、規模が大きくなると収拾がつかない。
* フレームワークに沿った書き方はできるけれど、自分ではじめからと言われると困ってしまう。

=== 身につくスキル

このテキストでは``Java``を利用しますが、考え方は他の言語でも利用することができます。
まずはじめに簡単なアプリを作り、そこに機能をどんどん追加していきます。
そのため、機能追加や変更に強いコーディングスキルを身につけることができます。

テキストの中盤をすぎる頃には、大規模なアプリケーションを構築することができるスキルを身につけることができるでしょう。

テキストの後半では、``Spring Framework``をアプリに適用します。
``Spring Framework``がどのような機能を持っていて、どのような目的をもって作られているのかを知ることができます。
もし、あなたがこの先、アプリを一から作ることになった場合でも``Spring Framework``を有効に使うことができます。

また、おまけ要素として、``Eclipse``のショートカットも載せていますから、
コーディングスピードの向上も期待できます。

=== このテキストの使い方
このテキストではいくつかの章で構成されていますが、
一つの章を終えると一通りの機能を持つアプリを手に入れることができます。
最後まで進めなくともアプリの完成を味わえます。

一つの賞は4つのセクションに分かれていて、それぞれセクションでは以下の内容が書かれています。
次のセクションに行く前に自分の頭で考えて見ることをおすすめします。

. お客様からどんなアプリを作って欲しいかの要望
. 要望を分解してどんなアプリを作るのかを設計する
. コーディングを行う上でのヒント
. コーディング例

=== 次のチャプターでは…

link:chapter1-1.html[Chapter 1 はじめてのアプリ]